{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "alatyr.fullname" . }}
  namespace: {{ .Values.serviceMonitor.promNs }}
  labels:
    {{- include "alatyr.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.promLabel }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "alatyr.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
{{- end }}
