apiVersion: v1
kind: Namespace
metadata:
  name: istio-mesh-a
  labels:
    kubernetes.io/metadata.name: istio-mesh-a
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-mesh-b
  labels:
    kubernetes.io/metadata.name: istio-mesh-b
    istio-injection: enabled
